{ self }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.beanKey;
  packages = self.packages.${pkgs.stdenv.hostPlatform.system};
  settings = import ./settings.nix {
    inherit
      cfg
      lib
      pkgs
      packages
      ;
  };
in
{
  options.programs.beanKey = settings.options;
  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      { inherit (settings) assertions; }
      (lib.mkIf pkgs.stdenv.hostPlatform.isLinux {
        i18n.inputMethod = import ./fcitx5.nix {
          inherit cfg lib packages;
        };
        home.packages = [ packages.daemon ];
        xdg.configFile."beankey/config.toml".source = settings.configFile;
      })
      (lib.mkIf pkgs.stdenv.hostPlatform.isDarwin {
        home.packages = [ packages.macos-input-method ];
        home.activation.beanKeyStandaloneConfig = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
          config_path="$HOME/Library/Application Support/beanKey/config.toml"
          if [[ -f "$config_path" && ! -L "$config_path" ]]; then
            marker=
            IFS= read -r marker < "$config_path" || true
            if [[ "$marker" == '# Generated by beanKey standalone installer' ]]; then
              backup_path="$config_path.standalone-backup"
              if [[ -e "$backup_path" || -L "$backup_path" ]]; then
                echo "beanKey: backup already exists: $backup_path" >&2
                exit 1
              fi
              if [[ ! -v DRY_RUN ]]; then
                mv "$config_path" "$backup_path"
              fi
            fi
          fi
        '';
        home.file."Library/Application Support/beanKey/config.toml".source = settings.configFile;
        home.activation.beanKeyInputMethod = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
          run ${packages.macos-input-method}/bin/beankey-install
        '';
      })
    ]
  );
}
