{ self }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.beanKey;
  packages = self.packages.${pkgs.stdenv.hostPlatform.system};
  settings = import ./settings.nix {
    inherit
      cfg
      lib
      pkgs
      packages
      ;
  };
  inputMethod = packages.macos-input-method;
in
{
  options.programs.beanKey = settings.options;
  config = lib.mkIf cfg.enable {
    assertions = settings.assertions ++ [
      {
        assertion = pkgs.stdenv.hostPlatform.isDarwin;
        message = "The beanKey Home Manager module requires macOS; use nixosModules.default on NixOS.";
      }
    ];
    home.packages = [ inputMethod ];
    home.activation.beanKeyStandaloneConfig = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
      config_path="$HOME/Library/Application Support/beanKey/config.toml"
      if [[ -f "$config_path" && ! -L "$config_path" ]]; then
        marker=
        IFS= read -r marker < "$config_path" || true
        if [[ "$marker" == '# Generated by beanKey standalone installer' ]]; then
          backup_path="$config_path.standalone-backup"
          if [[ -e "$backup_path" || -L "$backup_path" ]]; then
            echo "beanKey: backup already exists: $backup_path" >&2
            exit 1
          fi
          if [[ ! -v DRY_RUN ]]; then
            mv "$config_path" "$backup_path"
          fi
        fi
      fi
    '';
    home.file."Library/Application Support/beanKey/config.toml".source = settings.configFile;
    home.activation.beanKeyInputMethod = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
      run ${inputMethod}/bin/beankey-install
    '';
  };
}
